# Copyright © 2024 Atlantic Algorithms Ltd.,
# CoreChainDB and Atlantic Algorithms Ltd. software contributors.
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ngx-instance-0-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ngx-instance-0-dep
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: corechaindb/nginx_http:2.2.2
        imagePullPolicy: Always
        env:
        - name: NODE_FRONTEND_PORT
          valueFrom:
            configMapKeyRef:
              name: vars
              key: node-frontend-port
        - name: HEALTH_CHECK_PORT
          valueFrom:
            configMapKeyRef:
              name: vars
              key: node-health-check-port
        - name: DNS_SERVER
          valueFrom:
            configMapKeyRef:
              name: vars
              key: node-dns-server-ip
        - name: MONGODB_FRONTEND_PORT
          valueFrom:
            configMapKeyRef:
              name: vars
              key: mongodb-backend-port
        - name: MONGODB_BACKEND_HOST
          valueFrom:
            configMapKeyRef:
              name: vars
              key: ngx-mdb-instance-name
        - name: MONGODB_BACKEND_PORT
          valueFrom:
            configMapKeyRef:
              name: vars
              key: mongodb-backend-port
        - name: corechaindb_BACKEND_HOST
          valueFrom:
            configMapKeyRef:
              name: vars
              key: ngx-bdb-instance-name
        - name: corechaindb_API_PORT
          valueFrom:
            configMapKeyRef:
              name: vars
              key: corechaindb-api-port
        - name: corechaindb_WS_PORT
          valueFrom:
            configMapKeyRef:
              name: vars
              key: corechaindb-ws-port
        - name: TM_PUB_KEY_ACCESS_PORT
          valueFrom:
            configMapKeyRef:
              name: tendermint-config
              key: bdb-pub-key-access
        - name: TM_P2P_PORT
          valueFrom:
            configMapKeyRef:
              name: tendermint-config
              key: bdb-p2p-port
        ports:
        - containerPort: 8888
          protocol: TCP
          name: ngx-health
        - containerPort: 80
          protocol: TCP
        - containerPort: 9986
          protocol: TCP
          name: bdb-pub-key
        - containerPort: 26656
          protocol: TCP
          name: bdb-p2p-port
        livenessProbe:
          httpGet:
            path: /health
            port: ngx-health
          initialDelaySeconds: 15
          periodSeconds: 15
          failureThreshold: 3
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 768Mi
      restartPolicy: Always
