# Copyright © 2020, 2021 Interplanetary Database Association e.V.,
# CoreChainDB and Atlantic Algorithms Ltd. software contributors.
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

sudo: required

dist: focal

services:
  - docker

language: python
cache: pip

python:
  - 3.6
  - 3.7
  - 3.8

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.29.2
  matrix:
    - TOXENV=flake8
    - TOXENV=docsroot

matrix:
  fast_finish: true
  include:
  - python: 3.6
    env:
    - corechaindb_DATABASE_BACKEND=localmongodb
    - corechaindb_DATABASE_SSL=
  - python: 3.6
    env:
    - corechaindb_DATABASE_BACKEND=localmongodb
    - corechaindb_DATABASE_SSL=
    - corechaindb_CI_ABCI=enable
  - python: 3.6
    env:
    - corechaindb_ACCEPTANCE_TEST=enable
  - python: 3.7
    env:
    - corechaindb_DATABASE_BACKEND=localmongodb
    - corechaindb_DATABASE_SSL=
  - python: 3.7
    env:
    - corechaindb_DATABASE_BACKEND=localmongodb
    - corechaindb_DATABASE_SSL=
    - corechaindb_CI_ABCI=enable
  - python: 3.7
    env:
    - corechaindb_ACCEPTANCE_TEST=enable
  - python: 3.8
    env:
    - corechaindb_DATABASE_BACKEND=localmongodb
    - corechaindb_DATABASE_SSL=
  - python: 3.8
    env:
    - corechaindb_DATABASE_BACKEND=localmongodb
    - corechaindb_DATABASE_SSL=
    - corechaindb_CI_ABCI=enable
  - python: 3.8
    env:
    - corechaindb_ACCEPTANCE_TEST=enable


before_install: sudo .ci/travis-before-install.sh

install: .ci/travis-install.sh

before_script: .ci/travis-before-script.sh

script: .ci/travis_script.sh

after_success: .ci/travis-after-success.sh
