# Copyright © 2024 Atlantic Algorithms Ltd.,
# CoreChainDB and Atlantic Algorithms Ltd. software contributors.
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

---
- name: Install pymongo
  pip:
    name: pymongo
    state: present
  tags: [corechaindb]

- name: Install corechaindb
  shell: "python3.6 -m pip install -e /opt/stack/corechaindb/.[dev] --ignore-installed pyyaml"
  register: install_bdb
  failed_when: "'FAILED' in install_bdb.stderr or install_bdb.rc != 0"
  tags: [corechaindb]

- name: MongoDB Process Check
  shell: pgrep mongod | wc -l
  register: mdb_pchk
  tags: [corechaindb]

- name: Tendermint Process Check
  shell: pgrep tendermint | wc -l
  register: tm_pchk
  tags: [corechaindb]

- name: corechaindb Process Check
  shell: pgrep corechaindb | wc -l
  register: bdb_pchk
  tags: [corechaindb]

- name: Start corechaindb
  shell: nohup corechaindb -l DEBUG start > /tmp/corechaindb_log_$(date +%Y%m%d_%H%M%S) 2>&1 &
  environment:
    corechaindb_DATABASE_BACKEND: "localmongodb"
    corechaindb_DATABASE_HOST: "127.0.0.1"
    corechaindb_DATABASE_PORT: "27017"
    corechaindb_SERVER_BIND: "0.0.0.0:9984"
    corechaindb_WSSERVER_HOST: "0.0.0.0"
    corechaindb_WSSERVER_PORT: "9985"
    corechaindb_TENDERMINT_HOST: "127.0.0.1"
    corechaindb_TENDERMINT_PORT: "26657"
  when: mdb_pchk.stdout| int != 0 and bdb_pchk.stdout| int == 0 and tm_pchk.stdout| int != 0
  tags: [corechaindb]
